apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  labels:
    app: product-service
data:
  spring.application.name: product
  spring.datasource.url: jdbc:mysql://mysql:3306/ecommerce_product
  spring.datasource.name: product
  spring.datasource.password: product
  spring.datasource.driver-class-name: com.mysql.jdbc.Driver
